openapi: 3.0.0
info:
  title: AppVerify Code API - Get Data
  description: API endpoint for retrieving app's information using AVC Authkey.
  version: 1.0.0
servers:
  - url: https://avc.vercel.app
    description: Production server
paths:
  /api/getData:
    get:
      summary: Retrieve app's information.
      description: Retrieve app's information using AVC Authkey.
      parameters:
        - name: authkey
          in: query
          required: true
          description: Your app's AVC Authkey.
          schema:
            type: string
      responses:
        '200':
          description: Your app's information retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  restful_method:
                    type: string
                    example: GET
                  response_code:
                    type: string
                    example: '200'
                  authkey:
                    type: string
                    description: Your app's AVC Authkey.
                  status:
                    type: string
                    example: found
                  authkey_info:
                    type: object
                    properties:
                      tg_username:
                        type: string
                        description: Your Telegram's username.
                      tg_appname:
                        type: string
                        description: Your Telegram app's name.
                      tg_appbot:
                        type: string
                        description: Username of your app's bot.
        '400':
          description: Missing required parameter.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The 'authkey' parameter is required.
        '404':
          description: Authkey not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  restful_method:
                    type: string
                    example: GET
                  response_code:
                    type: string
                    example: '404'
                  error:
                    type: string
                    example: The provided 'authkey' was not found.
        '500':
          description: Internal server error (Database failure).
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unable to connect to MySQL database. Please contact the Administrator.
