openapi: 3.0.0
info:
  title: AppVerify Code API for Telegram - OTP Verification
  description: API endpoint for verifying OTP via Telegram bot.
  version: 1.0.0
servers:
  - url: https://avc.vercel.app
    description: Production server
paths:
  /api/telegram/otpVerification:
    post:
      summary: AppVerify Code API for Telegram - OTP Verification
      description: Send an OTP code to the user via AVCBot.
      parameters:
        - name: authkey
          in: query
          required: true
          description: Your app's AVC Authkey.
          schema:
            type: string
        - name: chatid
          in: query
          required: true
          description: User's Chat ID.
          schema:
            type: string
      responses:
        '200':
          description: OTP sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  restful_method:
                    type: string
                    example: POST
                  response_code:
                    type: string
                    example: '200'
                  status:
                    type: string
                    example: found
                  authkey_info:
                    type: object
                    properties:
                      tg_username:
                        type: string
                        description: Your Telegram's name.
                      tg_appname:
                        type: string
                        description: Your Telegram app's name.
                      tg_appbot:
                        type: string
                        description: Username of your app's bot.
                  sentTo:
                    type: object
                    properties:
                      chatid:
                        type: string
                        description: User's Chat ID.
                  verification_code:
                    type: integer
                    description: Generated OTP code.
        '400':
          description: Missing required parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The 'authkey' and 'chatid' parameters are required.
        '404':
          description: Authkey not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  restful_method:
                    type: string
                    example: POST
                  response_code:
                    type: string
                    example: '404'
                  error:
                    type: string
                    example: The provided 'authkey' was not found.
        '500':
          description: Internal server error (Database or Telegram API failure).
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unable to connect to MySQL database. Please contact the Administrator.
